config/routes.rb
Rails.application.routes.draw do
  resources :comments
  post "likes" => "likes#toggle"

  get "wall/:id" => "wall#show", as: :wall

  resources :posts do
    collection do
      get :paging
      get :insert_new
    end
  end

  get 'friends/my'
  get 'friends/friended_by'

  resources "messages" do
    collection do
      get :inbox
      get :sent
    end
  end

  get "friends" => "friends#index"
  get "profile" => "users#edit"
  # NOTE: /auth/facebook is supported by the omniauth-facebook gem

  get 'auth/:provider/callback' => 'sessions#callback'

  delete "remove_friend" => "friendships#destroy"
  resources :friendships

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  resources :users

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :sent_messages, class_name: "Message", foreign_key: "sender_id"
  has_many :received_messages, class_name: "Message", foreign_key: "recipient_id"

  has_many :posts, -> {order("updated_at DESC")}, dependent: :destroy, foreign_key: "poster_id"
  has_many :wall_posts, -> {order("updated_at DESC")}, dependent: :destroy, foreign_key: "wall_user_id", class_name: "Post"

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  mount_uploader :avatar, AvatarUploader

  # me ==> friendships
  # friendship ==> friend
  # friendships ==> friends

  validates :name, :email, presence: true
  has_secure_password

  def name_or_email
    name.presence || email
  end

  def self.from_omniauth(auth)
    # Check out the Auth Hash function at https://github.com/mkdynamic/omniauth-facebook#auth-hash
    # and figure out how to get email for this user.
    # Note that Facebook sometimes does not return email,
    # in that case you can use facebook-id@facebook.com as a workaround
    email = auth[:info][:email] || "#{auth[:uid]}@facebook.com"
    user = where(email: email).first_or_initialize
    if url = auth[:info][:image]
      user.remote_avatar_url = url.sub("http:", "https:") + "?type=large"
    end
    user.name = auth[:info][:name]
    user.password = SecureRandom.hex
    user.auth_hash = auth
    #
    # Set other properties on user here. Just generate a random password. User does not have to use it.
    # You may want to call user.save! to figure out why user can't save
    #
    # Finally:
    # - if user doesn't save, return false
    # - if user did save, return user
    user.save
    user
  end

  def image_url_or_default
    avatar.url || "http://lorempixel.com/128/128/sports/Fake-User/"
  end

  def add_friend(another_user)
    friends << another_user
  end

  def is_friend?(another_user)
    friends.include?(another_user)
  end

  def self.generate_users(n = 5, gender = "female")
    url = "https://randomuser.me/api?results=#{n}&gender=#{gender}"
    body = HTTP.get(url).parse
    body["results"].each do |person|
      hash = {gender: gender}
      hash[:name] = person["name"]["first"] + " " + person["name"]["last"]
      hash[:email] = person["email"]
      hash[:password] = person["login"]["password"]
      hash[:remote_avatar_url] = person["picture"]["large"]
      User.create! hash
    end
  end

  # EXPLANATION[]
  # def friends
  #   # go look at each of my friendship and get friend_id
  #   # then look up in User for the one with the id == friend_id
  #   results = []
  #   friendships.each do |fs|
  #     results << User.find(fs.friend_id)
  #   end
  #   results
  # end

  def friend_names
    friends.map{|e| e.name}
  end

  def friends_count
    friends.count
  end

  def inverse_friendships
    Friendship.where(friend_id: id)
  end

  # NOTE: this is inefficient
  def inverse_friends
    Friendship.where(friend_id: id).map{|e| e.user}
  end

  def inverse_friends_count
    inverse_friends.count
  end

  def male?
    gender == "male"
  end

  def toggle_like!(item)
    if like = likes.where(item: item).first
      like.destroy
    else
      likes.where(item: item).create!
    end
  end

  def likes?(item)
    likes.where(item: item).exists?
  end

  def self.random_user
    User.offset(rand(User.count)).first
  end

  def unseen_messages
    received_messages.unseen
  end

  def unseen_messages_count
    @unseen_messages_count ||= unseen_messages.count
  end

  def friends_by_count
    @friends_by_count ||= Friendship.where(friend_id: id).count
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:index]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      login(@user)
      redirect_to root_path, flash: {success: "User created."}
    else
      render 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    current_user.update(user_params)
    redirect_to root_path
  end

  def index
    @users = User.all.order("created_at DESC")
  end

  def search
    @users = User.autocomplete(params[:q])
    respond_to do |format|
      format.json
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :gender, :password_confirmation, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile_box.html.erb
<div class="box">
  <h1><%= icon("globe", "Intro") %></h1>
  <hr>
  <div><%= icon("briefcase", "Cofounder at CoderSchool") %></div>
  <div><%= icon("book", "Studied at Yale University") %></div>
</div>

<div class="box">
  <h1><%= icon("camera-retro", "Photos") %></h1>
</div>

<div class="box">
  <h1><%= icon("users", "Friends") %> <small class="tag"><%= user.friends_count %></small></h1>
</div>

app/views/users/_user_card.html.erb
<div class="card user-<%= user.gender %>">
  <div class="card-content">
    <article class="media">
      <figure class="media-left">
        <div class="image is-64x64">
          <%= image_tag user.image_url_or_default %>
        </div>
      </figure>
      <div class="media-content">
        <div>
          <div class="field">
            <span class="tag is-large">
              <span class="icon">
                <%= fa_icon(user.gender) %>
              </span>
              <%= link_to user.name, wall_path(user.id) %>
            </span>
          </div>
          <div class="field is-grouped">
            <div class="control">
              <div class="tags has-addons">
                <span class="tag">Friends</span>
                <span class="tag"><%= user.friends_count %></span>
              </div>
            </div>
            <div class="control">
              <div class="tags has-addons">
                <span class="tag">Friended by</span>
                <span class="tag"><%= user.inverse_friends_count %></span>
              </div>
            </div>
          </div>
        </div>
      </div> 
      <div class="media-right">
        <% if current_user.is_friend?(user) %>
          <%= link_to icon("user-times", "Unfriend", class: "icon is-small"), remove_friend_path(user_id: user.id), class: "button is-small add-remove", method: :delete %>
        <% else %>
          <%= form_for current_user.friendships.build(friend: user) do |f| %>
            <%= f.hidden_field :friend_id %>
            <button class="button is-small add-remove"><%= icon("user-plus", "Add friend", class: "icon is-small") %></button>
          <% end %>
        <% end %>
      </div>
    </article>
  </div>
</div>

app/views/users/edit.html.erb
<div class="content"><h1>Your Profile</h1></div>

<%= form_for @user do |f| %>
  <div class="columns">
    <div class="column is-one-third">
      <div class="field">
        <div class="label">Avatar</div>
        <div class="control"><%= f.file_field :avatar, class: "input" %></div>
      </div>
    </div>
    <div class="column is-one-third">
      <div class="card user-card">
        <div class="card-content">
          <div class="field">
            <div class="label">Name</div>
            <div class="control">
              <%= f.text_field :name, class: 'input' %>
            </div>
          </div>
          <div class="field">
            <div class="label">Email</div>
            <div class="control">
              <%= f.text_field :email, class: 'input' %>
            </div>
          </div>
          <div class="field">
            <div class="label">Gender</div>
            <div class="control">
              <%= f.text_field :gender, class: 'input' %>
            </div>
          </div>

          <div class="field">
            <div class="label">Password</div>
            <div class="control">
              <%= f.password_field :password, class: 'input' %>
            </div>
          </div>
          <%= f.submit "Update Profile", class: "button is-primary" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<h1 class="title">People</h1>

<% @users.in_groups_of(2, false).each do |group| %>
  <div class="columns">
  <% group.each do |user| %>
    <div class="column is-half">
      <%= render 'user_card', user: user %>
    </div>
  <% end %>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="columns">
  <div class="column is-one-third">
    <div class="card">
      <div class="card-header">
        <h1 class="card-header-title">Create An Account</h1>
      </div>
      <div class="card-content">
        <%= form_for @user do |f| %>
          <div class="field">
            <%= f.text_field :name, placeholder: "Name...", class: "input" %>
          </div>
          <div class="field">
            <%= f.text_field :email, placeholder: "Email...", class: "input" %>
          </div>
          <div class="field">
            <%= f.password_field :password, placeholder: "Password...", class: "input" %>
          </div>
          <div class="field">
            <%= f.submit "Register", class: "button is-primary" %>
          </div>
        <% end %>
      </div>
      <div class="card-footer">
      </div>
    </div>
  </div>