config/routes.rb
Rails.application.routes.draw do
  resources :comments
  post "likes" => "likes#toggle"

  get "wall/:id" => "wall#show", as: :wall

  resources :posts do
    collection do
      get :paging
      get :insert_new
    end
  end

  get 'friends/my'
  get 'friends/friended_by'

  resources "messages" do
    collection do
      get :inbox
      get :sent
    end
  end

  get "friends" => "friends#index"
  get "profile" => "users#edit"
  # NOTE: /auth/facebook is supported by the omniauth-facebook gem

  get 'auth/:provider/callback' => 'sessions#callback'

  delete "remove_friend" => "friendships#destroy"
  resources :friendships

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  resources :users

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    params[:per] ||= 10
    @posts = Post.order("updated_at DESC").page(params[:page]).per(params[:per])
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% unless current_user %>
  <%= link_to "Create An Account", new_user_path, class: "button is-primary" %>
  <%= link_to icon("facebook", "Log in with Facebook"), "/auth/facebook", class: "button is-info" %>
<% else %>
  <div class="columns is-mobile">
    <div class="column is-one-quarter">
      <aside class="menu">
        <ul class="menu-list">
          <li>
            <%= link_to wall_path(current_user), class: "wall-image-link" do %>
              <%= image_tag current_user.image_url_or_default, class: "icon" %>
              <%= current_user.name %>
            <% end %>
          </li>
        </ul>
        <p class="menu-label" style="margin-left: 1em">Apps</p>
        <ul class="menu-list">
          <li><%= link_to icon("newspaper-o", "News Feed"), root_path, class: "is-active" %></li>
          <li><%= link_to icon("comments-o", "Messenger"), messages_path %></li>
        </ul>
      </aside>
    </div>
    <div class="column is-two-thirds">
      <%= render "posts/form", post: Post.new(wall_user: current_user) %>
      <div class="js-posts">
        <%= render @posts %>
      </div>
      <div class="pagination" data-pagination-endpoint="<%= paging_posts_path %>" data-pagination-pages="<%= @posts.total_pages %>">
        <i class="fa fa-spinner fa-pulse fa-3x fa-fw" style="margin: auto"></i>
      </div>
    </div>
    <div class="column"></div>
  </div>
<% end %>