config/routes.rb
Rails.application.routes.draw do
  resources :comments
  post "likes" => "likes#toggle"

  get "wall/:id" => "wall#show", as: :wall

  resources :posts do
    collection do
      get :paging
      get :insert_new
    end
  end

  get 'friends/my'
  get 'friends/friended_by'

  resources "messages" do
    collection do
      get :inbox
      get :sent
    end
  end

  get "friends" => "friends#index"
  get "profile" => "users#edit"
  # NOTE: /auth/facebook is supported by the omniauth-facebook gem

  get 'auth/:provider/callback' => 'sessions#callback'

  delete "remove_friend" => "friendships#destroy"
  resources :friendships

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  resources :users

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :wall_user, class_name: "User"
  belongs_to :poster, class_name: "User"

  has_many :likes, as: :item, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :mentions, dependent: :destroy

  validates :body, presence: true

  mount_uploader :image, AvatarUploader

  def different_wall?
    wall_user != poster
  end

  def self.generate_posts(n = 5, user = nil, generate_mentions = true)
    user ||= User.last
    n.times do 
      post = Post.create(body: Faker::HowIMetYourMother.quote,
        wall_user: user,
        poster: User.random_user
      )
      rand(3).times do
        post.comments.create(
          body: Faker::HowIMetYourMother.catch_phrase,
          user: User.random_user
        )
      end 
      
      if generate_mentions
        rand(5).times do 
          post.mentions.create(
            user: User.random_user
          )
        end
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, only: [:create]
  before_action :set_access_headers

  def index
    params[:per] ||= 10
    @posts = Post.order("updated_at DESC").page(params[:page]).per(params[:per])

    respond_to do |format|
      format.json
    end
  end

  def show
    @post = Post.find params[:id]
    respond_to do |format|
      format.html
      format.json
    end
  end

  def create
    @post = current_user.posts.build post_params
    @post.wall_user ||= current_user

    if @post.save
      # PostMailer.new_post(@post).deliver
      # NotifySlack.new.notify_new_post(@post, url_for(@post))
      Broadcast.new_post(@post)
    else
      flash[:error] = @post.errors.full_messages.to_sentence
    end

    redirect_back fallback_location: root_path
  end

  def paging
    params[:per] ||= 10
    @posts = Post.order("updated_at DESC").page(params[:page]).per(params[:per])
    render @posts, layout: false
  end

  def insert_new
    @posts = Post.where("id >= ?", params[:post_id]).order("updated_at DESC")
    respond_to do |format|
      format.js
    end
  end

  private

  def post_params
    params.require(:post).permit(:body, :wall_user_id, :image)
  end

  def set_access_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, PUT, DELETE, GET, OPTIONS'
    headers['Access-Control-Request-Method'] = '*'
    headers['Access-Control-Allow-Headers'] = 'Origin, X-Requested-With, Content-Type, Accept, Authorization'
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_placeholder_message(post)
    if post.wall_user == current_user
      "What's on your mind, #{current_user.name}..."
    else
      "Write something to #{post.wall_user.name}..."
    end
  end

  def mentions_text(post)
      answer = ""
      if post.mentions.any?
        answer << "with #{post.mentions.first.user.name}"
        if post.mentions.count > 1
          num = " and #{pluralize(post.mentions.count - 1, "other")}"
          answer << num
        end
      end
      answer
  end
end

app/views/posts/_form.html.erb
<%= form_for post do |f| %>
  <%= f.hidden_field :wall_user_id %>
  <div class="card post">
    <div class="card-content">
      <div class="media">
        <div class="media-left">
          <p class="image is-32x32">
            <%= image_tag current_user.image_url_or_default %>
          </p>
        </div>
        <div class="media-content">
          <div class="field">
            <%= f.text_area :body, class: "textarea js-post-body", placeholder: post_placeholder_message(post), rows: "2" %>
          </div>
          <nav class="level is-mobile">
            <div class="level-left">
              <div class="level-item">
                <div class="file is-white">
                  <label class="file-label">
                    <%= f.file_field :image, class: "file-input" %>
                    <span class="file-cta">
                      <span class="file-icon">
                        <i class="fa fa-camera-retro"></i>
                      </span>
                      <span class="file-label">Photo…</span>
                    </span>
                  </label>
                </div>
              </div>
            </div>
            <div class="level-right">
              <div class="level-item">
                <label class="checkbox">
                  <input type="checkbox" class="js-enter-submit"> Press Enter to submit
                </label>
              </div>
              <button class="level-item button is-primary"><%= icon("send", "Post") %></button>
            </div>
          </nav>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_likes_sentence.html.erb
<div class="card-footer likes-sentence">
  <% if post.likes.present? %>
      <div>
        <%= fa_stacked_icon "thumbs-up inverse", base: "circle" %>
        <%= post.likes.map(&:user_name).to_sentence %>
      </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="js-post post card" id="<%= dom_id post %>" data-post-id="<%= post.id %>">
  <div class="card-content">
    <div class="media">
      <div class="media-left">
        <p class="image is-32x32">
          <%= image_tag post.poster.image_url_or_default %>
        </p>
      </div>
      <div class="media-content">
        <p class="is-title">
          <strong><%= link_to post.poster.name, wall_path(post.poster) %></strong>
          <% if post.different_wall? %>
            to
            <strong><%= link_to post.wall_user.name, wall_path(post.wall_user) %></strong>
          <% end %>
        </p>
        <small><%= time_ago_in_words post.updated_at %> ago</small>
      </div>
    </div>
    <div class="content">
      <%= simple_format post.body %>
    </div>
  </div>
  <% if post.image? %>
    <div class="card-image">
      <div class="image">
        <%= image_tag post.image.url %>
      </div>
    </div>
  <% end %>
  <div class="card-footer">
    <div class="level is-mobile">
      <div class="level-left">
        <div class="level-item">
          <%= link_to(icon("thumbs-up", "Like"), likes_path(post_id: post.id),
          class: "js-like-button button is-white #{'is-liked' if current_user && current_user.likes?(post)}",
          method: "post",
          remote: true
          ) %>
        </div>
        <div class="level-item">
          <%= link_to icon("comments", "Comment"), "#", class: "js-post-comment button is-white" %>
        </div>
      </div>
    </div>
  </div>
  <%= render "posts/likes_sentence", post: post %>
  <div class="comments">
    <%= render post.comments %>
  </div>
  <% if current_user %>
    <%= render "comments/form", comment: post.comments.build %>
  <% end %>
</div>

app/views/posts/insert_new.js.erb
$(".js-posts").prepend("<%= j render @posts %>");

app/views/posts/show.html.erb
<div class="container" style="padding: 20px">
  <%= render @post %>
</div>