config/routes.rb
Rails.application.routes.draw do
  resources :comments
  post "likes" => "likes#toggle"

  get "wall/:id" => "wall#show", as: :wall

  resources :posts do
    collection do
      get :paging
      get :insert_new
    end
  end

  get 'friends/my'
  get 'friends/friended_by'

  resources "messages" do
    collection do
      get :inbox
      get :sent
    end
  end

  get "friends" => "friends#index"
  get "profile" => "users#edit"
  # NOTE: /auth/facebook is supported by the omniauth-facebook gem

  get 'auth/:provider/callback' => 'sessions#callback'

  delete "remove_friend" => "friendships#destroy"
  resources :friendships

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  resources :users

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  include Trestle::Auth::ModelMethods
  include Trestle::Auth::ModelMethods::Rememberable
end

app/models/broadcast.rb
class Broadcast
  def self.new_post(post)
    ActionCable.server.broadcast "newsfeed", script: "PostsJs.updateNewsfeed(#{post.id})"
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :item, polymorphic: true

  def user_name
    user.name
  end
end

app/models/mention.rb
class Mention < ApplicationRecord
  belongs_to :user
  belongs_to :post

  # validates uniqueness of user and post 
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :recipient, class_name: 'User'
  validates :body, presence: true

  def self.unseen
    where(seen_at: nil)
  end

  def mark_as_seen!
    self.update_column :seen_at, Time.now
  end
end

app/models/notify_slack.rb
class NotifySlack
  def initialize
    @notifier = Slack::Notifier.new ENV["SLACK_WEBHOOK_URL"]
  end

  def notify_new_post(post, post_url = "/changeme")
    hash = {
      username: post.poster.name_or_email, 
      icon_url: post.poster.image_url_or_default
    }
    if post.image?
      hash[:attachments] = {
        title: post.body,
        title_link: post_url,
        image_url: post.image.url
      }
    end
    @notifier.ping(post.body, hash)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :wall_user, class_name: "User"
  belongs_to :poster, class_name: "User"

  has_many :likes, as: :item, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :mentions, dependent: :destroy

  validates :body, presence: true

  mount_uploader :image, AvatarUploader

  def different_wall?
    wall_user != poster
  end

  def self.generate_posts(n = 5, user = nil, generate_mentions = true)
    user ||= User.last
    n.times do 
      post = Post.create(body: Faker::HowIMetYourMother.quote,
        wall_user: user,
        poster: User.random_user
      )
      rand(3).times do
        post.comments.create(
          body: Faker::HowIMetYourMother.catch_phrase,
          user: User.random_user
        )
      end 
      
      if generate_mentions
        rand(5).times do 
          post.mentions.create(
            user: User.random_user
          )
        end
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :sent_messages, class_name: "Message", foreign_key: "sender_id"
  has_many :received_messages, class_name: "Message", foreign_key: "recipient_id"

  has_many :posts, -> {order("updated_at DESC")}, dependent: :destroy, foreign_key: "poster_id"
  has_many :wall_posts, -> {order("updated_at DESC")}, dependent: :destroy, foreign_key: "wall_user_id", class_name: "Post"

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  mount_uploader :avatar, AvatarUploader

  # me ==> friendships
  # friendship ==> friend
  # friendships ==> friends

  validates :name, :email, presence: true
  has_secure_password

  def name_or_email
    name.presence || email
  end

  def self.from_omniauth(auth)
    # Check out the Auth Hash function at https://github.com/mkdynamic/omniauth-facebook#auth-hash
    # and figure out how to get email for this user.
    # Note that Facebook sometimes does not return email,
    # in that case you can use facebook-id@facebook.com as a workaround
    email = auth[:info][:email] || "#{auth[:uid]}@facebook.com"
    user = where(email: email).first_or_initialize
    if url = auth[:info][:image]
      user.remote_avatar_url = url.sub("http:", "https:") + "?type=large"
    end
    user.name = auth[:info][:name]
    user.password = SecureRandom.hex
    user.auth_hash = auth
    #
    # Set other properties on user here. Just generate a random password. User does not have to use it.
    # You may want to call user.save! to figure out why user can't save
    #
    # Finally:
    # - if user doesn't save, return false
    # - if user did save, return user
    user.save
    user
  end

  def image_url_or_default
    avatar.url || "http://lorempixel.com/128/128/sports/Fake-User/"
  end

  def add_friend(another_user)
    friends << another_user
  end

  def is_friend?(another_user)
    friends.include?(another_user)
  end

  def self.generate_users(n = 5, gender = "female")
    url = "https://randomuser.me/api?results=#{n}&gender=#{gender}"
    body = HTTP.get(url).parse
    body["results"].each do |person|
      hash = {gender: gender}
      hash[:name] = person["name"]["first"] + " " + person["name"]["last"]
      hash[:email] = person["email"]
      hash[:password] = person["login"]["password"]
      hash[:remote_avatar_url] = person["picture"]["large"]
      User.create! hash
    end
  end

  # EXPLANATION[]
  # def friends
  #   # go look at each of my friendship and get friend_id
  #   # then look up in User for the one with the id == friend_id
  #   results = []
  #   friendships.each do |fs|
  #     results << User.find(fs.friend_id)
  #   end
  #   results
  # end

  def friend_names
    friends.map{|e| e.name}
  end

  def friends_count
    friends.count
  end

  def inverse_friendships
    Friendship.where(friend_id: id)
  end

  # NOTE: this is inefficient
  def inverse_friends
    Friendship.where(friend_id: id).map{|e| e.user}
  end

  def inverse_friends_count
    inverse_friends.count
  end

  def male?
    gender == "male"
  end

  def toggle_like!(item)
    if like = likes.where(item: item).first
      like.destroy
    else
      likes.where(item: item).create!
    end
  end

  def likes?(item)
    likes.where(item: item).exists?
  end

  def self.random_user
    User.offset(rand(User.count)).first
  end

  def unseen_messages
    received_messages.unseen
  end

  def unseen_messages_count
    @unseen_messages_count ||= unseen_messages.count
  end

  def friends_by_count
    @friends_by_count ||= Friendship.where(friend_id: id).count
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/navbar_helper.rb
module NavbarHelper
  def badge_nav_link(name, path, badge_count = "", options = {})
    options[:class] ||= ""
    options[:class] << " navbar-item js-messages-count"

    link_to path, options do
      badge_nav_link_content(badge_count)
    end
  end

  def badge_messages_count(user)
    badge_nav_link icon("comments-o"), messages_path, user.unseen_messages_count
  end

  def badge_nav_link_content(badge_count)
    name = icon("comments-o")
    if badge_count.to_i > 0
      content_tag(:span, name, class: "badge is-badge-danger", :"data-badge" => badge_count)
    else
      name
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_placeholder_message(post)
    if post.wall_user == current_user
      "What's on your mind, #{current_user.name}..."
    else
      "Write something to #{post.wall_user.name}..."
    end
  end

  def mentions_text(post)
      answer = ""
      if post.mentions.any?
        answer << "with #{post.mentions.first.user.name}"
        if post.mentions.count > 1
          num = " and #{pluralize(post.mentions.count - 1, "other")}"
          answer << num
        end
      end
      answer
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wall_helper.rb
module WallHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Humanbook</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <a class="navbar-item" href="/">
            <div class="image is-32x32" style="margin: 10px">
              <%= image_tag "human-1.png", alt: "Humanbook", style: "border-radius: 3px" %>
            </div>
          </a>
          <% if current_user %>
            <%= badge_nav_link icon("comments-o"), messages_path, current_user.unseen_messages_count, class: "is-hidden-desktop" %>
          <% end %>
          <div class="navbar-burger burger" data-target="navMenu">
            <span></span>
            <span></span>
            <span></span>
          </div>
        </div>
        <div class="navbar-menu" id="navMenu">
          <div class="navbar-start">
            <div class="navbar-item">
              <%= form_tag users_path, method: 'get' do %>
                <div class="field">
                  <div class="control has-icons-right">
                    <input class="input search-bar" type="text" placeholder="Search users" style="height:2em;width:30rem">
                    <span class="icon is-right is-small">
                      <%= fa_icon("search") %>
                    </span>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
          <div class="navbar-end">
            <% if current_user %>
              <%= link_to wall_path(current_user), class: "navbar-item" do %>
                <%= image_tag current_user.image_url_or_default %>
                &nbsp;<%= current_user.name %>
              <% end %>

              <div class="navbar-item has-dropdown is-hoverable">
                <%= link_to icon("users"), users_path, class: "navbar-link" %>
                <div class="navbar-dropdown">
                  <%= link_to "My Friends", friends_my_path, class: "navbar-item" %>
                  <%= link_to "Friended By", friends_friended_by_path, class: "navbar-item" %>
                </div>
              </div>

              <%= badge_nav_link icon("comments-o"), messages_path, current_user.unseen_messages_count %>
              <%= link_to icon("sign-out"), logout_path, class: "navbar-item" %>
            <% else %>
              <%= link_to "Sign Up", new_user_path, class: "navbar-item" %>
              <%= link_to "Log In", login_path, class: "navbar-item" %>
            <% end %>
          </div>
        </div>
      </nav>
    </div>
    <%= flash_messages %>

    <div class="container is-fluid" style="margin-top: 20px">
      <%= content_for?(:content) ? yield(:content) : yield %>
    </div>
  </body>
</html>

app/views/layouts/messages.html.erb
<% content_for :content do %>
  <div class="columns">
    <div class="column is-3">
      <aside class="menu">
        <p class="menu-label">
          Messages
        </p>
        <ul class="menu-list">
          <li><%= link_to icon("comment-o", "Compose"), new_message_path, class: "#{'is-active' if current_page?(new_message_path)}" %></li>
          <li><%= link_to icon("inbox", "Inbox"), inbox_messages_path, class: "#{'is-active' if current_page?(inbox_messages_path)}" %></li>
          <li><%= link_to icon("paper-plane-o", "Sent"), sent_messages_path, class: "#{'is-active' if current_page?(sent_messages_path)}" %></li>
        </ul>
      </aside>
    </div>
    <div class="column">
      <%= yield %>
    </div>
  </div>
<% end %>

<%= render file: "layouts/application" %>